# Generated by Django 4.1 on 2022-08-26 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.package'),
            preserve_default=False,
        ),
    ]
