# Generated by Django 4.1 on 2022-08-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_activity_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='code',
        ),
        migrations.RemoveField(
            model_name='userpackage',
            name='code',
        ),
        migrations.AddField(
            model_name='userpackage',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
