# Generated by Django 4.1 on 2022-08-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_userpackage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
