# Generated by Django 4.1 on 2022-08-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_userpackage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpackage',
            name='name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
