# Generated by Django 4.1 on 2022-08-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_userpackage_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPackage',
        ),
    ]
