# Generated by Django 4.1 on 2022-08-29 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_purchasepackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepackage',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
