# Generated by Django 4.1 on 2022-08-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_purchasepackage_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='packagedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
