# Generated by Django 4.1 on 2022-08-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_activity_packagedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='packagedate',
        ),
    ]
